# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-CD

on:
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  AZURE_RG: RG2
  AZURE_SUBSCRIPTION: 56384ba4-f818-473f-b624-70c2e39935df
  AZURE-LOCATION: WestEurope
jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
      - name: Publish 
        run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp }}/publish
